config:
  backup: true
  banner: true
  create: true
  dotpath: ../../.dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: true
dotfiles:
  d_config_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_zsh.d:
    src: zsh.d
    dst: ~/.zsh.d
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_config_termite_config:
    src: config/termite/config
    dst: ~/.config/termite/config
  f_config_ranger_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_config_code---oss_user_settings.json:
    src: config/Code - OSS/User/settings.json
    dst: ~/.config/Code - OSS/User/settings.json
profiles:
  work:
    dotfiles:
    - d_config_rofi
    - d_zsh.d
    - f_zshrc
    - f_config_termite_config
    - f_config_ranger_rc.conf
    - f_config_code---oss_user_settings.json
  home:
    dotfiles:
    - d_config_rofi
    - d_zsh.d
    - f_zshrc
    - f_config_termite_config
    - f_config_ranger_rc.conf
    - f_config_code---oss_user_settings.json
dynvariables:
  user: echo $USER
