config:
  backup: true
  banner: true
  create: true
  dotpath: ../../.dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_zsh.d:
    src: zsh.d
    dst: ~/.zsh.d
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_config:
    src: config/termite/config
    dst: ~/.config/termite/config
profiles:
  work:
    dotfiles:
    - d_rofi
    - d_zsh.d
    - f_zshrc
    - f_config
  home:
    dotfiles:
    - d_rofi
    - d_zsh.d
    - f_zshrc
    - f_config
dynvariables:
  user: echo $USER
